### ISSUE TITLE
Its slowly generate depthmap on my own dataset, 5s/img？？

### ISSUE THREAD

**Issue by gjd2017** [YadiraF/PRNet#120]

**Comment by ngoanpv** [comment]
I have the same problem, did you resolve it?

**Comment by gjd2017** [comment]
Use cython, https://github.com/YadiraF/face3d

**Comment by ngoanpv** [comment]
cython output depth image with the neck, I need depth image without the neck as same as PRNet output.
Do you any suggestion?

**Comment by gjd2017** [comment]
Use face with no neck.
