### ISSUE TITLE
Can I get 68 key points(landmarks) from the obj file?

### ISSUE THREAD

**Issue by fastcode3d** [YadiraF/PRNet#150]
Hi,
Is this feasible? If it's feasible, how should I get it?

Thanks a lot!

**Comment by fastcode3d** [comment]
I'm trying to map obj files to UV space, but I'm not sure if this is feasible. Has anyone tried anything like that?

**Comment by wanghaohotstar** [comment]
Hi! Have you solved the problem?I'm trying to do the same thing.

**Comment by wanghaohotstar** [comment]
> I'm trying to map obj files to UV space, but I'm not sure if this is feasible. Has anyone tried anything like that?

Hi! Have you solved the problem?I'm trying to do the same thing.

**Comment by fastcode3d** [comment]
Later I moved on to another project, and I didn't succeed in the attempt here

**Comment by Seven-Circles** [comment]
> Author

hi~can u share which project did you attempt?
