### ISSUE TITLE
Could Not use own images in demo.py throws No file found Error

### ISSUE THREAD

**Issue by cody4dev** [YadiraF/PRNet#178]
I tried running demo.py with my own images .
So I created 2 new folder named "images" and "outputs".
I saved an image in the "images" folder and tried executing the code :

````python demo.py -i images -o outputs --isDlib True````

But it threw an error saying 

````
File "C:\Users\DELL\Desktop\PRNet-master\utils\write.py", line 31, in write_obj_with_colors
    with open(obj_name, 'w') as f:
FileNotFoundError: [Errno 2] No such file or directory: 'outputs\\images\\faceimage9.obj'    
````

I even tried providing absolute path in the command like ,

```` python demo.py -i C:/prnet/images -o C;/prnet/output --isDlib True````

But yet nothing worked ..

Then I tried changing it in the error line with open(obj_name,w) to open("C;/prnet/images",w)

But then it displayed

```` with open("C:/prnet/outputs", 'bw') as f:
PermissionError: [Errno 13] Permission denied: 'C:/prnet/outputs' 
````

But the folder was by default given write permission .How could I solve this one ..

**Comment by meghnakidiya** [comment]
Do you find any solution??
