### ISSUE TITLE
The output models of demo are not so good...

### ISSUE THREAD

**Issue by wfly1998** [YadiraF/PRNet#42]
I've run the file `run_basics.py`, 0° faces can output wonderful models but the models all 90° faces output are not so good, so how to make it better?

**Comment by developer-mayuan** [comment]
@wfly1998 You can retrain the model or find a better solution if you don't like the result. Your question should not be considered as an issue (since you can run the code successfully).  Thanks.

**Comment by wfly1998** [comment]
I'm sorry but it's not the problem of whether I like the results or not, following is the result of the demo `image00475.jpg`.

![2018-06-20 20-38-59](https://user-images.githubusercontent.com/37299119/41658784-132103b8-74ca-11e8-9861-2c3d6b4c814f.png)
![2018-06-20 20-39-23](https://user-images.githubusercontent.com/37299119/41658786-137a16ba-74ca-11e8-93f5-b70386243932.png)

**Comment by jiegen** [comment]
@wfly1998 你好，方便给一下QQ之类的联系方式吗，我代码的运行还有一些问题，想请教一下您，非常感谢！

**Comment by wfly1998** [comment]
@jiegen 我看过你的issue了，README.md里面写着这个程序是在Python2.7下开发的，你的环境看起来像Python3.5，新建一个2.7的环境就好了。如果有需要可以加我微信，跟GitHub同号。
